### ISSUE TITLE
Loader throws error upon attempting to digest data

### ISSUE THREAD

**Issue by redstonedesigner** [richardthombs/scunpacked#93]
SC Version: 3.16.1
Windows Version: Windows 10 Pro 21H2
Loader Version: Latest

I followed the README guide on generating the data from the Data.p4k file, however on attempting to load a specific file, it doesn't like a value.  I've attempted to try the instructions however the error is thrown on the same file.

```
D:\Users\redstonedesigner\SC\Data\3.16.1\Raw\Data\Scripts\Entities\Vehicles\Implementations\Xml\CRUS_Starfighter.xml

Deserialisation failed while parsing Probability value "..6": Input string was not in a correct format.
Unhandled exception. System.InvalidOperationException: There is an error in the XML document.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Xml.XmlConvert.ToDouble(String s)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderVehicle.Read13_Part(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderVehicle.Read12_DamageBehavior(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderVehicle.Read13_Part(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderVehicle.Read13_Part(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderVehicle.Read18_Vehicle(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderVehicle.Read19_Vehicle()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at Loader.VehicleParser.ParseVehicle(String vehiclePath, String modificationName)
   at Loader.ShipLoader.LoadShip(String entityFilename)
   at Loader.ShipLoader.LoadFolder(String entityFolder, String shipFilter)
   at Loader.ShipLoader.Load(String shipFilter)
   at Loader.Program.Main(String[] args
```

**Comment by LeMyst** [comment]
https://github.com/richardthombs/scunpacked/issues/88

**Comment by damccull** [comment]
Yes it's a duplicate. You can manually remove the extra period from that file and it works fine. CIG will need to fix the source data to avoid this.
